micronaut:
    application:
        name: micronaut-revolut
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**

